### ISSUE TITLE
Can I use free local model like llama3 instead of openai key to run the code?

### ISSUE THREAD

**Issue by LieRenXZ** [bigai-ai/AdaSociety#1]
Can I use free local model like llama3 instead of openai key to run the code?

**Comment by j-alpha7** [comment]
Yes, absolutely! *AdaSociety* is providing the environment - it’s up to you how you want to power your agent.

If you’d like to use your own language model, you need to implement your own `Agent` class. Check out [this doc](https://github.com/bigai-ai/AdaSociety/tree/main/project/agent/README.md) for details on how to customize your agents. If you’re following our [LLM example](https://github.com/bigai-ai/AdaSociety/tree/main/project/tasks/llm), you can simply tweak the `update_policy()` function in `agent.py`. Replace the [planner](https://github.com/bigai-ai/AdaSociety/blob/main/project/tasks/llm/contract/agent/agent.py#L116) and the [query function](https://github.com/bigai-ai/AdaSociety/blob/main/project/tasks/llm/contract/agent/agent.py#L333) with one that interacts with your own local LLM, and you’re good to go!
